name: CI

on:
  push:
    branches: ["**/*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Test
        run: |
          [ $(sqlite3 db/pokemon.db 'select name from pokemon where generation_id = 1;' | wc -l | xargs) -eq 151 ]
      - uses: actions/upload-artifact@v4
        with:
          name: db
          path: db/pokemon.db
          if-no-files-found: error
  pre-release:
    runs-on: ubuntu-latest
    needs: build
    environment: pre-release
    if: github.ref_name == 'main'
    outputs:
      version: ${{ steps.prerelease.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/download-artifact@v4
        with:
          name: db
          path: db
      - id: prerelease
        name: PreRelease
        run: |
          set -eux
          export CURRENT_VERSION=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')

          tee version.ts <<EOF
          import { format, increment, parse } from "jsr:@std/semver";
          console.log(format(increment(parse(Deno.env.get("CURRENT_VERSION")), "prerelease")));
          EOF

          export NEXT_VERSION=$(deno run --allow-env version.ts)
          echo "VERSION=$NEXT_VERSION" >> "$GITHUB_OUTPUT"

          gh release create $NEXT_VERSION db/pokemon.db \
            --generate-notes \
            --notes 'Download `pokemon.db` from assets' \
            --prerelease
        env:
          GH_TOKEN: ${{ github.token }}
  release:
    runs-on: ubuntu-latest
    needs: pre-release
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Release
        run: |
          set -eux

          gh release edit $NEXT_VERSION --latest=true --prerelease=false
        env:
          GH_TOKEN: ${{ github.token }}
          NEXT_VERSION: ${{ needs.pre-release.outputs.version }}
