name: CI

on:
  push:
    branches: ["**/*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
        shell: bash
      - name: Test
        run: |
          [ $(sqlite3 db/pokemon.db 'select name from pokemon where generation_id = 1;' | wc -l | xargs) -eq 151 ]
        shell: bash
